/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class Lib {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Lib().getGreeting());
    }
}
